git:
  depth: 10
language: node_js
node_js:
- node
env:
  - FORMDATA_VERSION=2.3.1
before_script:
  - 'if [ "$FORMDATA_VERSION" ]; then npm install form-data@^$FORMDATA_VERSION; fi'
before_install: npm install -g npm
script: npm run coverage
cache:
  directories:
    - node_modules
